
{% set data = load_setup_py_data() %}

package:
    name: cookiecutter_example
    
    version: {{ data['version'] }}

source:
    path: ../

build:
    number: '0'

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        # dependencies are defined in setup.py
        {% for dep in data['install_requires'] %}
        - {{ dep.lower() }}
        {% endfor %}

about:
    home: https://github.com/ahendriksen/cookiecutter_example
    license_file: LICENSE.md
    summary: "Python CI CWI boilerplate package."

extra:
    maintainers:
        - Allard Hendriksne
